version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /tmp/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /tmp/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    ports:
     - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    # volumes:
    #   - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
