version: "3"

services:
  # mariadb:
  #   build:
  #     context: ./requirements/mariadb
  #     args:
  #       DB_NAME: ${MYSQL_DATABASE}
  #       DB_USER: ${MYSQL_USER}
  #       DB_PASS: ${MYSQL_PASSWORD}
  #       DB_ROOTPASS: ${MYSQL_ROOT_PASSWORD}
  #   container_name: mariadb
  #   env_file: .env
  #   volumes:
  #     - db:/var/lib/mysql
  #   networks:
  #     - inception

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #     args:
  #       DB_NAME: ${MYSQL_DATABASE}
  #       DB_USER: ${MYSQL_USER}
  #       DB_PASS: ${MYSQL_PASSWORD}
  #       DB_ROOTPASS: ${MYSQL_ROOT_PASSWORD}
  #   container_name: wordpress
  #   env_file: .env
  #   volumes:
  #     - wordpress:/var/www/html
  #   # depends_on:
  #   #   - mariadb
  #   networks:
  #     - inception

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    # depends_on:
    #   - wordpress
    ports:
      - 443:443
    networks:
      - inception

networks:
  inception:

volumes:
  db:
  wordpress: