FROM debian:buster

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y php7.3 php-fpm php-mysql mariadb-client

RUN apt-get -y install wget

RUN wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www

RUN cd /var/www && tar -xzf wordpress-6.0-fr_FR.tar.gz && rm wordpress-6.0-fr_FR.tar.gz

RUN	chown -R root:root /var/www/wordpress

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/wordpress

COPY ./tools/script.sh /tmp/script.sh

RUN chmod +x /tmp/script.sh

ENV WP_TITLE=MyBlog
ENV WP_ADMIN_USR=yed-dyb
ENV WP_ADMIN_PWD=wppass
ENV WP_ADMIN_EMAIL=dyb@example.com
ENV WP_USR=user1
ENV WP_EMAIL=user1@example.com
ENV WP_PWD=yed-dyb123
ENV MYSQL_HOSTNAME=mariadb
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=yed-dyb
ENV MYSQL_PASSWORD=wppass
ENV MYSQL_ROOT_PASSWORD=rootpass

CMD [ "sh", "/tmp/script.sh" ]
